services:
  #for local development we don't need the image directly.Uncomment if you want to use the image you built and choose local as env
  kitchenai_llama_index_chat_engine_best_mode:
    image: kitchenai_llama_index_chat_engine_best_mode
    ports:
    - "8000:8000"
    volumes:
      - $HOME/.aws/credentials:/root/.aws/credentials:ro
    network_mode: host
    environment:
      - OPENAI_API_KEY
    env_file:
      - .env
